export * from './number';
export * from './date';
export * from './type';
export * from './sleep';
declare const _default: {
    sleep(ms: number, msg?: string): Promise<unknown>;
    isArray(obj: any): boolean;
    isBoolean(obj: any): boolean;
    isDate(obj: any): boolean;
    isError(obj: any): boolean;
    isFunction(obj: any): boolean;
    isNull(obj: any): boolean;
    isNumber(obj: any): boolean;
    isRegExp(obj: any): boolean;
    isString(obj: any): boolean;
    isUndefined(obj: any): boolean;
    isObject(obj: any): boolean;
    deconstructDate(date: Date): {
        y: string;
        m: string;
        d: string;
        h: string;
        min: string;
        sec: string;
    };
    toChinaDate(date: Date): Date;
    toDateString(date: Date): string;
    toChinaDateString(date: Date): string;
    toChineseDateString(date: Date): string;
    toTimeString(date: Date): string;
    toChinaTimeString(date: Date): string;
    ts(date: Date): string;
    ts8(date: Date): string;
    ts6(date: Date): string;
    pad(num: number, len?: number): string;
    safeAdd(a: number, b: number): number;
    safeSub(a: number, b: number): number;
    safeMul(a: number, b: number): number;
    safeDiv(a: number, b: number): number;
};
export default _default;
